# Generated by Django 2.0 on 2018-11-02 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('zip', models.CharField(blank=True, max_length=5)),
                ('apt', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('parent', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Subject_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('grade', models.CharField(blank=True, max_length=4)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Teacher_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('level', models.CharField(blank=True, max_length=30)),
                ('teacher_comment', models.CharField(blank=True, max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=30)),
                ('course_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Teacher_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('credentials', models.CharField(blank=True, max_length=100)),
                ('subjects', models.ManyToManyField(blank=True, through='adminapp.Subject_Teacher_Relation', to='adminapp.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject_teacher_relation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Teacher'),
        ),
        migrations.AddField(
            model_name='student_teacher_relation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Teacher'),
        ),
        migrations.AddField(
            model_name='student_subject_relation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='adminapp.Student_Subject_Relation', to='adminapp.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, through='adminapp.Student_Teacher_Relation', to='adminapp.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
