# Generated by Django 2.0 on 2018-11-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20181103_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='picture',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
