# Generated by Django 2.0 on 2018-11-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.Notification'),
            preserve_default=False,
        ),
    ]
